### on GH

# setup rodrigue venv
cd  /home/jflucier/programs/Rodrigue_Lab
uv venv
source /home/jflucier/programs/Rodrigue_Lab/.venv/bin/activate
uv pip install biotite


# build RF container on GH
# salloc --partition=gh-bio --account=def-rodrigu1 --time=01:00:00 --gres=gpu:1 --cpus-per-task=8 --mem=30G
# singularity build --fakeroot rfdiffusion_gh200.sif rfdiffusion_gh200.def

## tests RF container
cd /home/jflucier/programs
git clone https://github.com/RosettaCommons/RFdiffusion.git
cd RFdiffusion

tar -xvf examples/ppi_scaffolds_subset.tar.gz -C examples/

singularity exec --nv \
-B /home/jflucier/programs/RFdiffusion:/home/jflucier/programs/RFdiffusion \
-B /home/jflucier/programs/RFdiffusion/schedules:/opt/RFdiffusion/schedules \
/home/jflucier/programs/Rodrigue_Lab/macrocyclic_design_pipeline/containers/rfdiffusion_gh200.sif \
python3 /opt/RFdiffusion/scripts/run_inference.py 'contigmap.contigs=[150-150]' inference.output_prefix=/home/jflucier/programs/RFdiffusion/examples/test_outputs/test inference.num_designs=10

#For an additional example of unconditional monomer generation, take a look at ./examples/design_unconditional.sh in the repo!

## build mpnn container
# generate github token
#How to Generate Your Git Token on GitHub
# Log into GitHub and click your profile picture in the upper-right corner.
# Click Settings.
# Scroll down the left sidebar and click Developer settings.
# Click Personal access tokens and select Tokens (classic)
# Click Generate new token -> Generate new token (classic).
# Give it a Note (e.g., "Rosetta CLI Access"), set an expiration date, and check the repo scope box.
# Scroll to the bottom and click Generate token.
# Important: Copy the token immediately and save it somewhere secure.

salloc --partition=gh-bio --account=def-rodrigu1 --time=01:00:00 --gres=gpu:1 --cpus-per-task=8 --mem=30G
cd /home/jflucier/programs
git clone https://<YOUR_TOKEN>@://github.com/RosettaCommons/rosetta.git
cd rosetta
git submodule update --init --recursive

singularity build --fakeroot \
rosetta_pyrosetta.sif rosetta_pyrosetta_build.def


