#!/usr/bin/env python
"""
01_build_rfpeptides_runs.py

Reads a TSV of targets (design_name, pdb_path, hotspots[, length]) and
writes one runnable shell script per row, each calling RFdiffusion's
run_inference.py with the RFpeptides macrocycle-binder flags
(inference.cyclic=True / inference.cyc_chains='a'), following:
https://github.com/RosettaCommons/RFdiffusion/blob/main/examples/design_macrocyclic_binder.sh
and Supplementary Methods 2.2.1 of Rettie, Juergens, Adebomi et al.,
Nat Chem Biol 2025.

This replaces the earlier RFD3-based version of this pipeline: as of the
current foundry docs, RFD3 does not expose an equivalent of
inference.cyclic/inference.cyc_chains, so macrocyclization stays on
RFdiffusion(v1) here.

TSV format (tab-separated, header required):
    design_name    pdb_path    hotspots              length
    MCL1_campaign  /path/mcl1.pdb   A224,A227,A252,A263,A266   16
    MDM2_campaign  /path/mdm2.pdb   A54,A57,A72,A93,A96        16-18

`hotspots`: comma-separated <chain><resnum> tokens, all on the same target
chain for a given row (this becomes ppi.hotspot_res).
`length` (optional): macrocycle length as a single int or "min-max".
Defaults to --default-length if the column is absent/blank for a row.
"""
import argparse
import csv
import sys
from pathlib import Path

try:
    import biotite.structure.io.pdb as pdb_io
    import biotite.structure.io.pdbx as pdbx_io
except ImportError:
    sys.exit("This script needs biotite: pip install biotite")

RUN_TEMPLATE = """#!/bin/bash
# Auto-generated by 01_build_rfpeptides_runs.py -- design: {design_name}
set -euo pipefail

{rfdiffusion_script} \\
    --config-name base \\
    inference.output_prefix={output_prefix} \\
    inference.num_designs={num_designs} \\
    'contigmap.contigs=[{length} {chain}{lo}-{hi}/0]' \\
    inference.input_pdb={pdb_path} \\
    inference.cyclic=True \\
    diffuser.T=50 \\
    inference.cyc_chains='a' \\
    'ppi.hotspot_res=[{hotspot_list}]'
"""


def load_structure(pdb_path: str):
    p = Path(pdb_path)
    if p.suffix.lower() in (".cif", ".mmcif"):
        cif = pdbx_io.CIFFile.read(str(p))
        return pdbx_io.get_structure(cif, model=1)
    f = pdb_io.PDBFile.read(str(p))
    return pdb_io.get_structure(f, model=1)


def chain_residue_range(structure, chain_id: str):
    mask = structure.chain_id == chain_id
    if not mask.any():
        raise ValueError(f"Chain '{chain_id}' not found in structure.")
    res_ids = structure.res_id[mask]
    return int(res_ids.min()), int(res_ids.max())


def parse_hotspots(hotspot_str: str):
    tokens = [t.strip() for t in hotspot_str.split(",") if t.strip()]
    chains = set()
    for tok in tokens:
        chains.add(tok[0])
    if len(chains) != 1:
        raise ValueError(
            f"All hotspots in one row must be on the same chain, got: {hotspot_str}"
        )
    return chains.pop(), tokens


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("targets_tsv")
    ap.add_argument("--out-dir", default="rfpeptides_runs",
                     help="Directory to write per-target run scripts + outputs into")
    ap.add_argument("--rfdiffusion-script", default="../scripts/run_inference.py",
                     help="Path to RFdiffusion's run_inference.py (relative to where "
                          "the generated run scripts will be executed from)")
    ap.add_argument("--default-length", default="10-14",
                     help="Macrocycle length used when a row has no 'length' column "
                          "(paper used 16 for MCL1, 16-18 for MDM2, 12-18 for "
                          "GABARAP/RbtA)")
    ap.add_argument("--num-designs", type=int, default=10000,
                     help="Backbones per target (paper used 10k for MCL1/MDM2, "
                          "20k for GABARAP/RbtA)")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(args.targets_tsv, newline="") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        required = {"design_name", "pdb_path", "hotspots"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            sys.exit(f"TSV missing required columns: {missing}")

        written = []
        for row in reader:
            name = row["design_name"].strip()
            if not name:
                continue
            pdb_path = row["pdb_path"].strip()
            hotspots_str = row["hotspots"].strip()
            length = (row.get("length") or "").strip() or args.default_length

            try:
                structure = load_structure(pdb_path)
                chain, hotspot_tokens = parse_hotspots(hotspots_str)
                lo, hi = chain_residue_range(structure, chain)
            except Exception as e:
                sys.exit(f"[{name}] failed to process: {e}")

            hotspot_list = ",".join(f"\\'{t}\\'" for t in hotspot_tokens)
            design_out_dir = out_dir / name
            design_out_dir.mkdir(exist_ok=True)

            script_text = RUN_TEMPLATE.format(
                design_name=name,
                rfdiffusion_script=args.rfdiffusion_script,
                output_prefix=str(design_out_dir / "diffused_binder_cyclic"),
                num_designs=args.num_designs,
                length=length,
                chain=chain, lo=lo, hi=hi,
                pdb_path=pdb_path,
                hotspot_list=hotspot_list,
            )
            script_path = out_dir / f"run_{name}.sh"
            script_path.write_text(script_text)
            script_path.chmod(0o755)
            written.append(script_path)

    print(f"Wrote {len(written)} run script(s) to {out_dir}/")
    for p in written:
        print(f"  {p}")
    print(
        "\nRun each script from wherever --rfdiffusion-script resolves correctly "
        "(e.g. RFdiffusion/examples/, matching the upstream example), or pass an "
        "absolute path to --rfdiffusion-script and run from anywhere."
    )


if __name__ == "__main__":
    main()
