### on GH

# build container on GH
# salloc --partition=gh-bio --account=def-rodrigu1 --time=01:00:00 --gres=gpu:1 --cpus-per-task=8 --mem=30G
# singularity build --fakeroot rfdiffusion_gh200.sif rfdiffusion_gh200.def

## tests
cd /home/jflucier/programs
git clone https://github.com/RosettaCommons/RFdiffusion.git
cd RFdiffusion

tar -xvf examples/ppi_scaffolds_subset.tar.gz -C examples/

singularity exec \
-B /home/jflucier/programs/RFdiffusion:/home/jflucier/programs/RFdiffusion \
/home/jflucier/programs/Rodrigue_Lab/macrocyclic_design_pipeline/containers/rfdiffusion_gh200.sif \
python3 /opt/RFdiffusion/scripts/run_inference.py 'contigmap.contigs=[150-150]' inference.output_prefix=/home/jflucier/programs/RFdiffusion/examples/test_outputs/test inference.num_designs=10

#For an additional example of unconditional monomer generation, take a look at ./examples/design_unconditional.sh in the repo!

